package org.fog.test.perfeval;

import org.cloudbus.cloudsim.core.CloudSim;
import org.fog.application.AppEdge;
import org.fog.application.AppLoop;
import org.fog.application.Application;
import org.fog.application.selectivity.FractionalSelectivity;
import org.fog.entities.*;
import org.fog.placement.ModuleMapping;
import org.fog.placement.ModulePlacementEdgewards;
import org.fog.utils.FogLinearPowerModel;
import org.fog.utils.FogUtils;
import org.fog.utils.TimeKeeper;
import org.fog.utils.distribution.DeterministicDistribution;

import java.util.*;

/**
 * ECG Offloading Application — iFogSim2 Integration
 * ===================================================
 * Chennai 4-Zone Edge-Fog-Cloud Topology
 * with QSO-POA allocation and OOBL-PRO cloud routing.
 *
 * This file is the iFogSim2 counterpart to the Python pipeline.
 * The Python modules (Days 1-4) generate task parameters.
 * This Java class simulates those tasks in iFogSim2.
 *
 * TOPOLOGY:
 *   Cloud (1) -> Proxy/Chennai-Gateway (1) ->
 *   Fog Nodes (4: central, south, west, north) ->
 *   Edge Nodes (4: one per zone) ->
 *   IoT Sensors (12: 3 per edge zone)
 *
 * THREE MICROSERVICES (following reference thesis architecture):
 *   1. clientModule        : IoT wearable / smartphone
 *   2. preprocessingModule : Edge node — feature extraction + complexity scoring
 *   3. decisionModule      : Edge (simple tasks) or Cloud (complex/critical)
 *
 * TASK CLASSES (from Python Day 1 pipeline):
 *   Class 0 — Simple   : MI=800-1200,  RAM=10MB  -> Edge pre-screening
 *   Class 1 — Moderate : MI=1500-3000, RAM=25MB  -> Edge pre-screening
 *   Class 2 — Complex  : MI=3000-5000, RAM=40MB  -> Cloud full diagnosis
 *   Class 3 — Critical : MI=5000,      RAM=50MB  -> Cloud forced (ST>0.31mV)
 *
 * HOW TO RUN:
 *   1. Set up Maven project with iFogSim2 dependency
 *   2. Place this file in src/main/java/org/fog/test/perfeval/
 *   3. Also add QSOPOAAllocator.java and OOBLPRORouter.java (see below)
 *   4. Run main() method
 *
 * REFERENCE: Adapted from reference thesis simulation framework
 *            (Shinu M.R., Amrita Vishwa Vidyapeetham, 2024)
 */
public class ECGOffloadingApplication {

    // ── Cluster task parameters (from Python Day 1 + Day 2 output) ──────────
    // These values come from cluster_centroids.csv generated by Day 2
    // Cluster 0: Clean normal (8.9% of windows)
    static final long   CLUSTER0_MI  = 1021;
    static final int    CLUSTER0_RAM = 10;
    static final double CLUSTER0_BW  = 100.0;

    // Cluster 1: Rhythmically complex (81.4% of windows)
    static final long   CLUSTER1_MI  = 2699;
    static final int    CLUSTER1_RAM = 32;
    static final double CLUSTER1_BW  = 320.0;

    // Cluster 2: Morphologically abnormal (9.8% of windows)
    static final long   CLUSTER2_MI  = 1206;
    static final int    CLUSTER2_RAM = 12;
    static final double CLUSTER2_BW  = 123.0;

    // ECG transmission: 5-second window at 360Hz = 1800 samples
    // At 16-bit resolution = 3600 bytes = 3.6KB per window
    // Transmission interval = 5 seconds
    static final double ECG_TRANSMISSION_TIME = 5.0; // seconds

    // ── Node MIPS values (from Python Day 3 topology) ───────────────────────
    static final int MIPS_CLOUD     = 44800;
    static final int MIPS_PROXY     = 2800;
    static final int MIPS_FOG       = 2800;
    static final int MIPS_EDGE      = 1000;
    static final int MIPS_IOT       = 100;

    // ── MI scaling factors (tiered processing architecture) ─────────────────
    // Edge:  5% MI  (pre-screening)
    // Fog:   30% MI (intermediate classification)
    // Cloud: 100% MI (full diagnosis)
    static final double MI_SCALE_EDGE  = 0.05;
    static final double MI_SCALE_FOG   = 0.30;
    static final double MI_SCALE_CLOUD = 1.00;

    // ── Simulation parameters ────────────────────────────────────────────────
    static List<FogDevice>    fogDevices   = new ArrayList<>();
    static List<Sensor>       sensors      = new ArrayList<>();
    static List<Actuator>     actuators    = new ArrayList<>();
    static int                userId;
    static String             appId        = "ecg_offloading";

    // ── QSO-POA Allocator (see QSOPOAAllocator.java) ────────────────────────
    static QSOPOAAllocator allocator = new QSOPOAAllocator();

    public static void main(String[] args) {
        System.out.println("=".repeat(65));
        System.out.println("ECG Offloading Application — iFogSim2");
        System.out.println("Chennai 4-Zone Topology");
        System.out.println("=".repeat(65));

        try {
            // Step 1: Initialize CloudSim
            int numUsers = 1;
            Calendar cal = Calendar.getInstance();
            CloudSim.init(numUsers, cal, false);

            // Step 2: Create application
            Application app = createApplication(appId, userId);
            app.setUserId(userId);

            // Step 3: Create fog devices (topology)
            FogDevice cloud   = createCloud();
            FogDevice proxy   = createProxy("proxy-chennai", cloud.getId());
            FogDevice fogC    = createFog("fog-central",  proxy.getId());
            FogDevice fogS    = createFog("fog-south",    proxy.getId());
            FogDevice fogW    = createFog("fog-west",     proxy.getId());
            FogDevice fogN    = createFog("fog-north",    proxy.getId());
            FogDevice edgeC   = createEdge("edge-central", fogC.getId());
            FogDevice edgeS   = createEdge("edge-south",   fogS.getId());
            FogDevice edgeW   = createEdge("edge-west",    fogW.getId());
            FogDevice edgeN   = createEdge("edge-north",   fogN.getId());

            fogDevices.addAll(Arrays.asList(
                cloud, proxy, fogC, fogS, fogW, fogN,
                edgeC, edgeS, edgeW, edgeN
            ));

            // Store edge node IDs for QSO-POA allocator
            allocator.setEdgeNodes(Arrays.asList(
                edgeC.getId(), edgeS.getId(), edgeW.getId(), edgeN.getId()
            ));
            allocator.setCloudNodeId(cloud.getId());

            // Step 4: Create IoT sensors (3 per edge zone = 12 total)
            createSensorsForEdge(edgeC, 3, appId);
            createSensorsForEdge(edgeS, 3, appId);
            createSensorsForEdge(edgeW, 3, appId);
            createSensorsForEdge(edgeN, 3, appId);

            // Step 5: Module placement (using QSO-POA allocation)
            ModuleMapping moduleMapping = createModuleMapping(
                edgeC, edgeS, edgeW, edgeN, cloud
            );

            // Step 6: Run simulation
            Controller controller = new Controller(
                "master-controller", fogDevices, sensors, actuators
            );
            controller.submitApplication(
                app,
                new ModulePlacementEdgewards(
                    fogDevices, sensors, actuators, app, moduleMapping
                )
            );

            TimeKeeper.getInstance().setSimulationStartTime(
                Calendar.getInstance().getTimeInMillis()
            );

            CloudSim.startSimulation();
            CloudSim.stopSimulation();

            // Step 7: Print results
            printResults();

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // ────────────────────────────────────────────────────────────────────────
    // DEVICE CREATION
    // ────────────────────────────────────────────────────────────────────────

    /**
     * Creates the cloud datacenter node.
     * MIPS=44800 (AWS Mumbai / Azure India South equivalent)
     * Uplink latency=0 (top of hierarchy — no further uplink)
     * 100ms represents WAN round-trip from Chennai to cloud
     */
    static FogDevice createCloud() throws Exception {
        FogDevice cloud = createFogDevice(
            "cloud",
            MIPS_CLOUD,  // MIPS
            40000,       // RAM (MB)
            10000,       // uplink bandwidth (Kbps)
            10000,       // downlink bandwidth (Kbps)
            0,           // uplink latency (ms) — top of hierarchy
            16 * 103,    // busy power (W) — reference thesis value
            16 * 83.25   // idle power (W)
        );
        cloud.setParentId(-1); // no parent
        return cloud;
    }

    /**
     * Creates the Chennai city-level proxy/gateway node.
     * Acts as regional aggregator between fog zones and cloud.
     * Uplink latency=100ms (WAN to cloud)
     */
    static FogDevice createProxy(String name, int parentId) throws Exception {
        FogDevice proxy = createFogDevice(
            name, MIPS_PROXY, 4000, 5000, 5000,
            100,            // uplink latency to cloud (WAN = 100ms)
            107.339, 83.4333
        );
        proxy.setParentId(parentId);
        proxy.setUplinkLatency(100);
        return proxy;
    }

    /**
     * Creates a fog node (hospital-grade server at zone level).
     * MIPS=2800 (same as proxy — hospital server class hardware)
     * Uplink latency=15ms (metro fiber to proxy/gateway)
     */
    static FogDevice createFog(String name, int parentId) throws Exception {
        FogDevice fog = createFogDevice(
            name, MIPS_FOG, 4000, 1000, 1000,
            15,             // uplink latency to proxy (metro fiber)
            107.339, 83.4333
        );
        fog.setParentId(parentId);
        fog.setUplinkLatency(15);
        return fog;
    }

    /**
     * Creates an edge node (clinical gateway device).
     * MIPS=1000 (Intel NUC / Raspberry Pi 4 class hardware)
     * Uplink latency=3ms (LAN within hospital zone)
     */
    static FogDevice createEdge(String name, int parentId) throws Exception {
        FogDevice edge = createFogDevice(
            name, MIPS_EDGE, 1000, 500, 500,
            3,              // uplink latency to fog (LAN = 3ms)
            107.339, 83.4333
        );
        edge.setParentId(parentId);
        edge.setUplinkLatency(3);
        return edge;
    }

    /**
     * Core FogDevice factory method.
     * Follows reference thesis parameter structure.
     */
    static FogDevice createFogDevice(
            String name, int mips, int ram,
            long uplinkBw, long downlinkBw,
            double uplinkLatency,
            double busyPower, double idlePower) throws Exception {

        List<Pe> peList = new ArrayList<>();
        peList.add(new Pe(0, new PeProvisionerOverbooking(mips)));

        int hostId = FogUtils.generateEntityId();
        long storage = 1000000; // 1TB
        int bw = 10000;

        PowerHost host = new PowerHost(
            hostId,
            new RamProvisionerSimple(ram),
            new BwProvisionerOverbooking(bw),
            storage,
            peList,
            new StreamOperatorScheduler(peList),
            new FogLinearPowerModel(busyPower, idlePower)
        );

        List<Host> hostList = new ArrayList<>();
        hostList.add(host);

        String arch = "x86";
        String os = "Linux";
        String vmm = "Xen";
        double timeZone = 5.5; // IST
        double costPerSec = 3.0;
        double costPerMem = 0.05;
        double costPerStorage = 0.1;
        double costPerBw = 0.1;

        FogDeviceCharacteristics chars = new FogDeviceCharacteristics(
            arch, os, vmm, host, timeZone,
            costPerSec, costPerMem, costPerStorage, costPerBw
        );

        FogDevice device = new FogDevice(
            name, chars,
            new AppModuleAllocationPolicy(hostList),
            new LinkedList<>(),
            10,
            uplinkBw, downlinkBw,
            uplinkLatency,
            0.01  // rate per MIPS (cost model)
        );

        return device;
    }

    // ────────────────────────────────────────────────────────────────────────
    // SENSOR CREATION
    // ────────────────────────────────────────────────────────────────────────

    /**
     * Creates ECG wearable sensors connected to a given edge node.
     * Each sensor transmits one 5-second ECG window every 5 seconds.
     * Transmission time = 5ms (BLE/WiFi to edge device).
     *
     * DeterministicDistribution(5.0) means exactly one transmission
     * every 5 seconds — deterministic, not random.
     * This matches the reference thesis sensor configuration.
     */
    static void createSensorsForEdge(FogDevice edge, int count, String appId) {
        for (int i = 0; i < count; i++) {
            String sensorName = "ecg-sensor-" + edge.getName() + "-" + i;
            Sensor sensor = new Sensor(
                sensorName,
                "ECG_SENSOR",
                userId,
                appId,
                new DeterministicDistribution(ECG_TRANSMISSION_TIME)
            );
            sensor.setGatewayDeviceId(edge.getId());
            sensor.setLatency(5.0); // 5ms BLE/WiFi transmission latency
            sensors.add(sensor);
        }
    }

    // ────────────────────────────────────────────────────────────────────────
    // APPLICATION DEFINITION
    // ────────────────────────────────────────────────────────────────────────

    /**
     * Defines the three-microservice application topology.
     *
     * AppModules (microservices):
     *   clientModule        : Captures ECG, sends to preprocessing
     *   preprocessingModule : Computes complexity score, assigns task class
     *   decisionModule      : Classification (edge for simple, cloud for complex)
     *
     * AppEdges (data flows):
     *   ECG_SENSOR -> clientModule        : raw sensor data
     *   clientModule -> preprocessingModule : 5-sec ECG window (1800 samples)
     *   preprocessingModule -> decisionModule : feature vector + task class
     *   decisionModule -> clientModule      : classification result (feedback)
     *
     * AppLoops (latency measurement):
     *   ECG_SENSOR -> clientModule -> preprocessingModule -> decisionModule
     *   (end-to-end latency measured from sensor to final decision)
     *
     * CPU lengths for AppEdges correspond to tiered MI scaling:
     *   clientModule edge:        100 MI (data capture, minimal compute)
     *   preprocessingModule edge: 500 MI (complexity scoring — edge 5%)
     *   decisionModule edge:      MI from cluster centroid (full or scaled)
     */
    static Application createApplication(String appId, int userId) {
        Application app = Application.createApplication(appId, userId);

        // Add modules
        // RAM values from task parameter assignments (Day 1)
        app.addAppModule("clientModule",        10,  100,  100);
        app.addAppModule("preprocessingModule", 512, 500,  200);
        app.addAppModule("decisionModule",      2048, (int)CLUSTER1_MI, 500);

        // Add edges (data flows between modules)
        // fractionalSelectivity: fraction of input tuples that produce output

        // Sensor -> Client
        app.addAppEdge(
            "ECG_SENSOR", "clientModule",
            100,                    // tuple CPU length (MI)
            CLUSTER1_BW,           // tuple file size (bytes → BW)
            "ECG_SENSOR",          // tuple type
            Tuple.UP,              AppEdge.SENSOR
        );

        // Client -> Preprocessing
        app.addAppEdge(
            "clientModule", "preprocessingModule",
            (long)(CLUSTER1_MI * MI_SCALE_EDGE * 10),  // 5% MI for pre-processing
            CLUSTER1_BW,
            "ECG_WINDOW",
            Tuple.UP,              AppEdge.MODULE
        );

        // Preprocessing -> Decision
        app.addAppEdge(
            "preprocessingModule", "decisionModule",
            CLUSTER1_MI,           // Full MI for decision module
            CLUSTER1_BW,
            "TASK_FEATURES",
            Tuple.UP,              AppEdge.MODULE
        );

        // Decision -> Client (result feedback)
        app.addAppEdge(
            "decisionModule", "clientModule",
            14,                    // small result tuple
            CLUSTER1_BW,
            "ECG_RESULT",
            Tuple.DOWN,            AppEdge.MODULE
        );

        // Add selectivity (fraction of tuples that flow through)
        app.addTupleMapping(
            "clientModule",        "ECG_SENSOR",   "ECG_WINDOW",    new FractionalSelectivity(1.0)
        );
        app.addTupleMapping(
            "preprocessingModule", "ECG_WINDOW",   "TASK_FEATURES", new FractionalSelectivity(1.0)
        );
        app.addTupleMapping(
            "decisionModule",      "TASK_FEATURES","ECG_RESULT",    new FractionalSelectivity(1.0)
        );
        app.addTupleMapping(
            "clientModule",        "ECG_RESULT",   "ECG_SENSOR",    new FractionalSelectivity(1.0)
        );

        // Define end-to-end latency measurement loop
        List<String> loopModules = Arrays.asList(
            "clientModule", "preprocessingModule", "decisionModule"
        );
        app.addAppLoop(new AppLoop(loopModules));

        return app;
    }

    // ────────────────────────────────────────────────────────────────────────
    // MODULE PLACEMENT (QSO-POA INTEGRATION)
    // ────────────────────────────────────────────────────────────────────────

    /**
     * Creates module placement mapping using QSO-POA decisions.
     *
     * For each task cluster, QSO-POA has decided which specific edge
     * node handles it. We map the decision module to those edge nodes
     * for simple/moderate clusters, and to cloud for complex/critical.
     *
     * This is where the Python Day 4 output (allocation_results.csv)
     * feeds into the Java simulation.
     *
     * In full integration: read allocation_results.csv and map
     * each cluster's assigned node here. For now, uses NSGA-II result
     * (all clusters → edge tier, QSO-POA distributes among edge nodes).
     */
    static ModuleMapping createModuleMapping(
            FogDevice edgeC, FogDevice edgeS,
            FogDevice edgeW, FogDevice edgeN,
            FogDevice cloud) {

        ModuleMapping mapping = ModuleMapping.createModuleMapping();

        // clientModule: runs on all edge nodes (close to IoT sensors)
        mapping.addModuleToDevice("clientModule", edgeC.getName());
        mapping.addModuleToDevice("clientModule", edgeS.getName());
        mapping.addModuleToDevice("clientModule", edgeW.getName());
        mapping.addModuleToDevice("clientModule", edgeN.getName());

        // preprocessingModule: runs on edge nodes (complexity scoring)
        mapping.addModuleToDevice("preprocessingModule", edgeC.getName());
        mapping.addModuleToDevice("preprocessingModule", edgeS.getName());
        mapping.addModuleToDevice("preprocessingModule", edgeW.getName());
        mapping.addModuleToDevice("preprocessingModule", edgeN.getName());

        // decisionModule: QSO-POA determined edge allocation
        // Cluster 0 (simple) -> edge-south  (from Day 4 output)
        // Cluster 1 (moderate) -> edge-west  (from Day 4 output)
        // Cluster 2 (morphological) -> edge-north (from Day 4 output)
        // Cluster 3 (critical) -> cloud (forced)
        mapping.addModuleToDevice("decisionModule", edgeS.getName());  // Cluster 0
        mapping.addModuleToDevice("decisionModule", edgeW.getName());  // Cluster 1
        mapping.addModuleToDevice("decisionModule", edgeN.getName());  // Cluster 2
        mapping.addModuleToDevice("decisionModule", cloud.getName());  // Cluster 3

        return mapping;
    }

    // ────────────────────────────────────────────────────────────────────────
    // RESULTS
    // ────────────────────────────────────────────────────────────────────────

    static void printResults() {
        System.out.println("\n" + "=".repeat(65));
        System.out.println("SIMULATION RESULTS");
        System.out.println("=".repeat(65));

        System.out.println("\nApp Loop Latencies (end-to-end ms):");
        for (Integer loopId : TimeKeeper.getInstance().getLoopIdToCurrentAverage().keySet()) {
            double avg = TimeKeeper.getInstance().getLoopIdToCurrentAverage().get(loopId);
            System.out.printf("  Loop %d: %.4f ms%n", loopId, avg);
        }

        System.out.println("\nEnergy Consumed per Fog Device:");
        for (FogDevice dev : fogDevices) {
            System.out.printf("  %-20s: %.4f mJ%n",
                dev.getName(), dev.getEnergyConsumption());
        }

        double totalEnergy = fogDevices.stream()
            .mapToDouble(FogDevice::getEnergyConsumption).sum();
        System.out.printf("%n  TOTAL ENERGY: %.4f mJ%n", totalEnergy);

        System.out.println("\n[NEXT STEP] Implement OOBL-PRO for cloud overflow routing");
    }
}


// =============================================================================
// QSOPOAAllocator.java — separate file
// =============================================================================
// NOTE: Save this as a separate file: QSOPOAAllocator.java
// in the same package: org.fog.test.perfeval
//
// This Java class mirrors the Python QSO-POA logic for iFogSim2 integration.
// In full deployment, this runs in real-time as tasks arrive.

/*
package org.fog.test.perfeval;

import java.util.*;

public class QSOPOAAllocator {

    private List<Integer> edgeNodeIds = new ArrayList<>();
    private int cloudNodeId = -1;

    // Current load on each edge node (fraction 0-1)
    private Map<Integer, Double> nodeLoad = new HashMap<>();

    private static final double SATURATION_THRESHOLD = 0.80;
    private static final int    QSO_POPULATION       = 20;
    private static final int    QSO_ITERATIONS       = 30;
    private static final int    POA_ITERATIONS       = 15;
    private static final double QSO_ALPHA            = 0.5;

    public void setEdgeNodes(List<Integer> ids) {
        this.edgeNodeIds = ids;
        for (int id : ids) nodeLoad.put(id, 0.0);
    }

    public void setCloudNodeId(int id) { this.cloudNodeId = id; }

    // Main allocation method — called for each incoming task
    public int allocate(long taskMI, double taskBW, int taskClass) {
        // Critical task -> cloud immediately
        if (taskClass == 3) return cloudNodeId;

        // Get available (non-saturated) edge nodes
        List<Integer> available = getAvailableNodes();

        // All saturated -> cloud overflow
        if (available.isEmpty()) return cloudNodeId;

        // QSO: global exploration
        int qsoBest = qsoExplore(taskMI, taskBW, available);

        // POA: local refinement
        int poaBest = poaRefine(qsoBest, taskMI, taskBW, available);

        // Update load
        updateLoad(poaBest, taskMI);

        return poaBest;
    }

    private int qsoExplore(long mi, double bw, List<Integer> available) {
        // Initialize population
        List<Integer> pop = new ArrayList<>();
        Random rnd = new Random();
        for (int i = 0; i < QSO_POPULATION; i++) {
            pop.add(available.get(rnd.nextInt(available.size())));
        }

        int    gBest    = pop.get(0);
        double gBestFit = fitness(gBest, mi, bw);

        for (int iter = 0; iter < QSO_ITERATIONS; iter++) {
            // Build probability weights
            double[] weights = new double[available.size()];
            double totalW = 0;
            for (int i = 0; i < available.size(); i++) {
                weights[i] = 1.0 / (fitness(available.get(i), mi, bw) + 1e-9);
                totalW += weights[i];
            }
            for (int i = 0; i < weights.length; i++) weights[i] /= totalW;

            // Update population
            List<Integer> newPop = new ArrayList<>();
            for (int nodeId : pop) {
                int newNode;
                if (rnd.nextDouble() < QSO_ALPHA) {
                    // Social learning: sample from weighted distribution
                    newNode = weightedSample(available, weights, rnd);
                } else {
                    newNode = available.get(rnd.nextInt(available.size()));
                }
                newPop.add(newNode);
                double f = fitness(newNode, mi, bw);
                if (f < gBestFit) { gBest = newNode; gBestFit = f; }
            }
            pop = newPop;
        }
        return gBest;
    }

    private int poaRefine(int startNode, long mi, double bw,
                          List<Integer> available) {
        int    best    = startNode;
        double bestFit = fitness(best, mi, bw);
        double step    = 0.3;

        for (int iter = 0; iter < POA_ITERATIONS; iter++) {
            boolean improved = false;
            for (int nid : available) {
                if (nid == best) continue;
                double f = fitness(nid, mi, bw);
                if (f < bestFit - step * 0.01) {
                    best    = nid;
                    bestFit = f;
                    improved = true;
                }
            }
            step *= 0.9;
            if (!improved) break;
        }
        return best;
    }

    private double fitness(int nodeId, long mi, double bw) {
        double load   = nodeLoad.getOrDefault(nodeId, 0.0);
        double effMI  = mi * 0.05; // 5% pre-screening
        double latency = (effMI / 1000.0) * 1000.0 + 1.0; // ms
        double energy  = effMI * 0.02;
        double loadPenalty = Math.max(0, (load - 0.5) / 0.5);
        return 0.5 * (latency / 270.0) + 0.3 * (energy / 5.0) + 0.2 * loadPenalty;
    }

    private List<Integer> getAvailableNodes() {
        List<Integer> available = new ArrayList<>();
        for (int id : edgeNodeIds) {
            if (nodeLoad.getOrDefault(id, 0.0) < SATURATION_THRESHOLD) {
                available.add(id);
            }
        }
        return available;
    }

    private void updateLoad(int nodeId, long mi) {
        double current = nodeLoad.getOrDefault(nodeId, 0.0);
        // Simple load model: MI processed / node capacity per window
        double capacity = 1000.0 * 500.0; // MIPS * batch_duration_sec
        nodeLoad.put(nodeId, Math.min(current + (mi * 0.05 / capacity), 1.0));
    }

    private int weightedSample(List<Integer> items, double[] weights, Random rnd) {
        double r = rnd.nextDouble();
        double cumulative = 0;
        for (int i = 0; i < items.size(); i++) {
            cumulative += weights[i];
            if (r <= cumulative) return items.get(i);
        }
        return items.get(items.size() - 1);
    }
}
*/